package rad.technologies.greensense.genrelUtills;
//R.A.D. Technologies
public class Config {
    public static final String MY_PREF = "grubs-up";

    public static String BASEURL = "http://api.divergense.com/grabs/api/";
    public static String FilterItems = "http://api.divergense.com/kcall/api/getItems/search";
    public static String Add_MoreInfo = "http://api.divergense.com/kcall/api/addMoreInfo";



    public static String token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjE4ZDIyODk2OGExY2JjZTdhNTAzMzMwNzgxNjYxNDQ5OGM5YjllMThjN2JmY2Q0NDQ1Nzg0MzBhMzZmYTJmMTQxMWQ1YWY5NWNmMmZmM2I1In0.eyJhdWQiOiIxIiwianRpIjoiMThkMjI4OTY4YTFjYmNlN2E1MDMzMzA3ODE2NjE0NDk4YzliOWUxOGM3YmZjZDQ0NDU3ODQzMGEzNmZhMmYxNDExZDVhZjk1Y2YyZmYzYjUiLCJpYXQiOjE1NTAwNzQ1ODAsIm5iZiI6MTU1MDA3NDU4MCwiZXhwIjoxNTgxNjEwNTgwLCJzdWIiOiIzIiwic2NvcGVzIjpbXX0.bbwYcgKAxSwfXmU6_61w34CzF5IhvgMNKXfmCno5PZbOm2OQOvSHiQKdST2uxh4BYngxh-_Xosu1KBmXgVJWnL8JwHgNZDa_gdWYbmuO3zNgrKkWXqn8cqVdkdYtzBwSBnjsPG_fC-ppjhaPWfeopDcjAf0vnRKaFOrjRK_1Jwf8-SYJ9yIyqSIaK2MfJOspiw0k4eKbWc4Sv3s-I5THSAI-MLvrLTHTANg6EJVTQhG2CDLJKGhIhM5js81CqFVVYoyWawA-M7IG8cYn0Hh3jAUIcRErQ_8FZ4FpMBVQQBwwAFxP9nf9CGletEYXyoKEDbhHj3d2YDnff079z42ZyFGNCZIYXwXKinf9QVbLqUUa2FqNtGbp5zapsVn_SEyl6u37CNLr62YqnMlTc0QwpEnPXZ1MdzLbvEm-VRp9AGMNR-VbgCxNWTcYFo4qKentqonMioRN5xfVxFT6CuX3oKp_9TPJXKGS6EgBYvu52_fwjXZj6svhE5QyHt9ZTPxpCSV1JVlMKHkHjab7Hj69gpNf-0D-CTeb-byOQo6Nep0KoDPwkgnZLGpQfwPC0ANSAoHhgTklIExp11kMcpERZ1NOwndQyKYZzSlwtSPzc_0STS6dP74p6bJFFR9JLGObJofRsh9qz2SqpiAM4BLB_G5a1e7rW3oAqDNRbLj4HUo";
}
